### ISSUE TITLE
Can you add a `CHANGELOG.md` or at least GitHub release?

### ISSUE THREAD

**Issue by JounQin** [d3x0r/JSOX#14]
Besides, `v1.2.119` is not tagged yet.

https://github.com/d3x0r/JSOX/tags

I suggest to use https://github.com/changesets/changesets for changelog and releasing stuffs.

**Comment by d3x0r** [comment]
https://github.com/d3x0r/JSOX/blob/master/README.md#changelog ?
added tag
The readme changelog then shows the changes on npm page too

**Comment by JounQin** [comment]
OK, thanks for letting me know where changelog is. But it's still too deep to be discovered without a TOC.

**Comment by d3x0r** [comment]
other than it's at the end....so I don't know 'deep' :)  ya a TOC might be a good addition

**Comment by JounQin** [comment]
> other than it's at the end....so I don't know 'deep' :) ya a TOC might be a good addition

Yes, `end` is the problem, and I won't expect whole changelogs list in README.MD personally, so I suggest to move the section content into a new `CHANGELOG.md` file instead, and just link it at the end of README.

**Comment by d3x0r** [comment]
I appreciate the comment, when(if) there's another change I'll consider it more... the primary motivation for keeping it in the readme was visibility on NPM, if there was a link it'd have to be an absolute link to github, but I've also had it hosted on other servers, and a relative link doesn't work, because npmjs.org only extracts the readme.  a TOC is a good compromise; but the naive implementation takes a good chunk of space... I had found a tool that autogenerated a TOC to the side of a .md, but I didn't really like how complex that turned out to be, and I haven't been using that.
some changelogs have gotten quite large, and could use maybe truncation into a changelod.md and just the last half-dozen entries or so kept in the readme; but then there's still not a good relative link I can use.

https://www.npmjs.com/package/sack.vfs an even worse example; I broke out sections into separate readme's and then there's a external links to github.  Which isn't an entirely terrible idea, just isn't great either.

Closing for now as - to be considered (feel free to comment more though).
